remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Code For Thought
description: Blogs, News and other bits for the Code for Thought Podcast
show_downloads: false
